# -*- coding: utf-8 -*-
"""
Deterministic Unit Tests for core/analyzer.py Pipeline:
  1. Candlestick & BPA Bar Pattern Classifications
  2. analyze_stock Pipeline & Support/Resistance Levels
  3. analyze_stock_5m Intraday BPA, Conformal Noise Filter & MTF Resonance
"""

import unittest
from unittest.mock import patch
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

from core.analyzer import analyze_stock, analyze_stock_5m, classify_candlestick_patterns


class TestBarPatternRecognition(unittest.TestCase):
    """Verify all 11+ candlestick and BPA patterns generated by production classify_candlestick_patterns."""

    def test_trend_and_reversal_bars(self):
        """Test bull/bear trend bars and bull/bear reversal bars directly invoking production classifier."""
        df = pd.DataFrame({
            "open": [100.0, 100.0, 109.0, 101.0, 104.0],
            "high": [102.0, 110.0, 110.0, 106.0, 112.0],
            "low":  [99.0,   99.5, 100.0,  95.0, 101.0],
            "close":[101.0, 109.0, 100.5, 105.0, 102.0],
            "ema20":[100.0, 101.0, 102.0, 100.0, 103.0]
        })

        res_df = classify_candlestick_patterns(df)

        self.assertIn("多頭趨勢棒(Bull Trend)", res_df["bpa_bar_type"].iloc[1])
        self.assertIn("空頭趨勢棒(Bear Trend)", res_df["bpa_bar_type"].iloc[2])
        self.assertTrue(res_df["bull_rev_bar"].iloc[3], "Bar 3 must be Bull Reversal Bar")
        self.assertIn("多頭反轉棒(Bull Reversal)", res_df["bpa_bar_type"].iloc[3])
        self.assertTrue(res_df["bear_rev_bar"].iloc[4], "Bar 4 must be Bear Reversal Bar")
        self.assertIn("空頭反轉棒(Bear Reversal)", res_df["bpa_bar_type"].iloc[4])

    def test_inside_and_outside_bars(self):
        """Test Inside Bar, Double Inside Bar (ii), Outside Bar, and Doji via production classifier."""
        df = pd.DataFrame({
            "open": [100.0, 104.0, 104.5, 103.0, 105.0],
            "high": [112.0, 107.0, 106.0, 110.0, 108.0],
            "low":  [101.0, 103.0, 104.0,  99.0, 102.0],
            "close":[106.0, 105.0, 105.0, 107.0, 105.2],
        })

        res_df = classify_candlestick_patterns(df)

        self.assertTrue(res_df["inside_bar"].iloc[1], "Bar 1 must be Inside Bar")
        self.assertIn("孕線(Inside Bar)", res_df["bpa_bar_type"].iloc[1])
        self.assertTrue(res_df["double_inside"].iloc[2], "Bar 2 must be Double Inside (ii)")
        self.assertIn("雙重孕線(ii 突破模式)", res_df["bpa_bar_type"].iloc[2])
        self.assertTrue(res_df["outside_bar"].iloc[3], "Bar 3 must be Outside Bar")
        self.assertIn("外部棒(Outside Bar)", res_df["bpa_bar_type"].iloc[3])
        self.assertTrue(res_df["doji_bar"].iloc[4], "Bar 4 must be Doji")
        self.assertIn("十字猶豫棒(Doji)", res_df["bpa_bar_type"].iloc[4])

    def test_engulfing_hammer_and_star(self):
        """Test Bullish/Bearish Engulfing, Hammer, and Shooting Star patterns via production classifier."""
        df = pd.DataFrame({
            "open": [105.0, 101.0, 102.0, 100.0],
            "high": [106.0, 108.0, 102.5, 110.0],
            "low":  [101.0,  99.0,  95.0,  99.8],
            "close":[102.0, 107.0, 102.0, 100.2],
        })

        res_df = classify_candlestick_patterns(df)

        self.assertTrue(res_df["bull_engulf"].iloc[1], "Bar 1 must be Bullish Engulfing")
        self.assertTrue(res_df["hammer"].iloc[2], "Bar 2 must be Hammer")
        self.assertTrue(res_df["star"].iloc[3], "Bar 3 must be Shooting Star")


class TestAnalyzeStockPipeline(unittest.TestCase):
    """End-to-end execution of analyze_stock with mocked data feeds."""

    def _generate_synthetic_records(self, n=60):
        base_date = datetime(2026, 1, 1)
        records = []
        for i in range(n):
            d = base_date + timedelta(days=i)
            records.append({
                "date": d.strftime("%Y-%m-%d"),
                "open": 100.0 + i * 0.5,
                "high": 102.0 + i * 0.5,
                "low": 98.0 + i * 0.5,
                "close": 101.0 + i * 0.5,
                "volume": 1000.0 + (i % 5) * 100.0
            })
        return records

    @patch("core.analyzer.get_info", return_value=("tse", "台積電"))
    @patch("core.analyzer.fetch_twse")
    @patch("core.analyzer.fetch_realtime_bar", return_value=None)
    @patch("core.analyzer.fetch_institutional", return_value=pd.DataFrame())
    @patch("core.analyzer.fetch_fundamentals", return_value={"revenue_yoy": 20.0, "eps_ttm": 5.0, "gross_margin": 40.0})
    def test_analyze_stock_full_pipeline(self, mock_fund, mock_inst, mock_rt, mock_twse, mock_info):
        """Verify analyze_stock calculates all indicators and returns proper data dictionary."""
        mock_twse.return_value = self._generate_synthetic_records(60)

        res = analyze_stock("2330", months=3, generate_html=False, print_report=False)

        self.assertIn("df", res)
        self.assertIn("bpa_res", res)
        self.assertIn("trend_score", res)
        self.assertIn("trend_stage", res)
        self.assertIn("rating_badge", res)
        self.assertIn("sr_levels", res)
        self.assertIn("composite_rating", res)

        # Check technical indicators computed
        df = res["df"]
        for ma_col in ["ma5", "ma20", "ma60"]:
            self.assertIn(ma_col, df.columns)
        self.assertIn("rsi", df.columns)
        self.assertIn("macd", df.columns)
        self.assertIn("macd_signal", df.columns)
        self.assertIn("kd_k", df.columns)
        self.assertIn("kd_d", df.columns)
        self.assertIn("bb_upper", df.columns)
        self.assertIn("bb_lower", df.columns)

        # Check S/R levels
        sr = res["sr_levels"]
        self.assertGreaterEqual(sr["r1"], sr["s1"])
        self.assertGreaterEqual(sr["r2"], sr["s2"])


class TestAnalyzeStock5m(unittest.TestCase):
    """Unit tests for analyze_stock_5m: Conformal Prediction, MTF, and Whale Patterns."""

    def _generate_5m_raw(self, n=50, noise_mult=1.0, is_bull=True, vol_mult=1.0):
        dates = pd.date_range("2026-09-10 09:00", periods=n, freq="5min", tz="Asia/Taipei")
        closes = [100.0 + i * (0.2 if is_bull else -0.2) for i in range(n)]
        opens = [c - 0.1 for c in closes]
        highs = [c + 0.3 * noise_mult for c in closes]
        lows  = [c - 0.3 * noise_mult for c in closes]
        vols  = [100.0 * 1000.0] * (n - 1) + [100.0 * 1000.0 * vol_mult]

        return pd.DataFrame({
            "open": opens,
            "high": highs,
            "low": lows,
            "close": closes,
            "volume": vols
        }, index=dates)

    @patch("core.analyzer.get_info", return_value=("tse", "台積電"))
    @patch("yfinance.download")
    @patch("core.analyzer.analyze_stock")
    def test_conformal_noise_extreme_rejection(self, mock_daily, mock_yf, mock_info):
        """Conformal prediction: noise ratio > 2.8x triggers 🛑 拒絕開倉 (雜訊過大)."""
        raw = self._generate_5m_raw(n=50, noise_mult=1.0)
        # Make the last bar an extreme wild spike (5x ATR)
        raw.iloc[-1, raw.columns.get_loc("high")] = raw.iloc[-1]["close"] + 5.0
        raw.iloc[-1, raw.columns.get_loc("low")] = raw.iloc[-1]["close"] - 5.0

        mock_yf.return_value = raw
        mock_daily.return_value = {"bpa_res": {"always_in_code": "AIL"}, "trend_score": 3, "df": pd.DataFrame({"ma20": [100.0]})}

        res = analyze_stock_5m("2330", days=1)

        self.assertIn("🛑 拒絕開倉", res["action_tag"])
        self.assertIn("雜訊過大", res["conformal_status"])

    @patch("core.analyzer.get_info", return_value=("tse", "台積電"))
    @patch("yfinance.download")
    @patch("core.analyzer.analyze_stock")
    def test_conformal_volatility_dull_pause(self, mock_daily, mock_yf, mock_info):
        """Conformal prediction: noise ratio < 0.35x triggers 🛑 暫緩開倉 (動能不足/空間狹窄)."""
        raw = self._generate_5m_raw(n=50, noise_mult=1.0)
        # Make the last bar completely flat (0.01 range)
        last_c = raw.iloc[-1]["close"]
        raw.iloc[-1, raw.columns.get_loc("open")] = last_c
        raw.iloc[-1, raw.columns.get_loc("high")] = last_c + 0.02
        raw.iloc[-1, raw.columns.get_loc("low")] = last_c - 0.02

        mock_yf.return_value = raw
        mock_daily.return_value = {"bpa_res": {"always_in_code": "AIL"}, "trend_score": 3, "df": pd.DataFrame({"ma20": [100.0]})}

        res = analyze_stock_5m("2330", days=1)

        self.assertIn("🛑 暫緩開倉", res["action_tag"])
        self.assertIn("波動過低", res["conformal_status"])

    @patch("core.analyzer.get_info", return_value=("tse", "台積電"))
    @patch("yfinance.download")
    @patch("core.analyzer.analyze_stock")
    def test_mtf_daily_bear_suppresses_5m_bull(self, mock_daily, mock_yf, mock_info):
        """MTF alignment: when Daily is AIS (bearish), 5m bull must NOT give BUY signal, but '逆日線弱彈'."""
        raw = self._generate_5m_raw(n=50, noise_mult=1.0, is_bull=True)
        mock_yf.return_value = raw
        # Daily is AIS
        mock_daily.return_value = {
            "bpa_res": {"always_in_code": "AIS"},
            "trend_score": -4,
            "df": pd.DataFrame({"ma20": [150.0]})  # close < daily_ma20
        }

        res = analyze_stock_5m("2330", days=1)

        self.assertIn("逆日線弱彈", res["action_tag"])
        self.assertIn("逆日線弱彈", res["mtf_status"])

    @patch("core.analyzer.get_info", return_value=("tse", "台積電"))
    @patch("yfinance.download")
    @patch("core.analyzer.analyze_stock")
    def test_mtf_daily_and_5m_bull_resonance(self, mock_daily, mock_yf, mock_info):
        """MTF resonance: Daily AIL + 5m AIL triggers '🔥 建議順勢做多'."""
        raw = self._generate_5m_raw(n=50, noise_mult=1.0, is_bull=True)
        mock_yf.return_value = raw
        # Daily is AIL
        mock_daily.return_value = {
            "bpa_res": {"always_in_code": "AIL"},
            "trend_score": 5,
            "df": pd.DataFrame({"ma20": [90.0]})  # close > daily_ma20
        }

        res = analyze_stock_5m("2330", days=1)

        self.assertIn("建議順勢做多", res["action_tag"])
        self.assertIn("雙時框多方共振", res["mtf_status"])

    @patch("core.analyzer.get_info", return_value=("tse", "台積電"))
    @patch("yfinance.download")
    @patch("core.analyzer.analyze_stock")
    def test_whale_volume_surge_patterns(self, mock_daily, mock_yf, mock_info):
        """Whale volume surge (vol >= 1.8x vol_ma20): triggers whale tagging."""
        # 2.5x volume on last bar
        raw = self._generate_5m_raw(n=50, noise_mult=1.0, is_bull=True, vol_mult=2.5)
        # Ensure last bar is a solid bull trend bar with body/rng >= 0.5
        c = raw.iloc[-1]["close"]
        raw.iloc[-1, raw.columns.get_loc("open")] = c - 0.4
        raw.iloc[-1, raw.columns.get_loc("high")] = c + 0.1
        raw.iloc[-1, raw.columns.get_loc("low")] = c - 0.45

        mock_yf.return_value = raw
        mock_daily.return_value = {"bpa_res": {"always_in_code": "AIL"}, "trend_score": 3, "df": pd.DataFrame({"ma20": [90.0]})}

        res = analyze_stock_5m("2330", days=1)

        self.assertIn("主力放量推升", res["whale_tag"])
        self.assertGreaterEqual(res["vol_ratio_5m"], 1.8)


if __name__ == "__main__":
    unittest.main()
